# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b2803101ffa04ed06b0075ec350bbfd306abc5da2b02bb72e2227c6ddbfc6de0f31657490777a3922bcc43773722d4b4bfdc4311a5264e5ce9bda83c1324ad2

test:
  secret_key_base: 10c116ff0781c654eea7af6967a69922fe365098f02fbfbb12eb7cb4989c698deaa893d798a5e0f9273bc6e28e34ac384873d6affa162f8f00474fec138bf3c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
